dependencies:
  - name: initializer
    version: 0.5.0
    # repository: file://../initializer
    condition: initializer.enabled
  - name: mixer
    version: 0.5.0
    # repository: file://../mixer
    condition: mixer.enabled
  - name: pilot
    version: 0.5.0
    # repository: file://../pilot
    condition: pilot.enabled
  - name: security
    version: 0.5.0
    # repository: file://../security
    condition: global.securityEnabled
