apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:serviceaccount:kube-system:default
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:serviceaccount:kube-system:default 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:serviceaccount:kube-system:default 
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
