name: istio-crds
version: 0.3.0
description: Helm chart to deploy CRD definitions
keywords:
  - istio
  - crd
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
